collections:
  - name: page
    label: Page
    category: Content
    folder: content
    fields:
      - {"label": "Title", "name": "title", "widget": "string", "required": true}
      - {"label": "Body", "name": "body", "widget": "markdown"}
      - {
        "label": "Tags",
        "default": [ "Design" ],
        "max": 2,
        "min": 1,
        "multiple": true,
        "name": "tags",
        "options": [ "Design", "UX", "Dev" ],
        "widget": "select"
        }

  - name: resource
    label: Resource
    category: Content
    folder: content
    fields:
      - {"label": "Title", "name": "title", "widget": "string", "required": true}
      - {"label": "Description", "name": "description", "widget": "text"}
      - {"label": "File", "name": "file", "widget": "file"}

  - name: metadata
    label: Metadata
    category: Settings
    files:
      - file: data/metadata.json
        name: sitemetadata
        label: Site Metadata
        fields:
          - { "label": "Course Title", "name": "title", "widget": "text", "required": true }
          - {
            "label": "Course Description",
            "name": "description",
            "widget": "markdown",
            "minimal": true,
            "help": "A description of the course that will be shown on the course site home page."
          }
          - { "label": "Tags", "default": [ "Design" ], "max": 3, "min": 1, "multiple": true, "name": "tags", "options": [ "Design", "UX", "Dev" ], "widget": "select" }
          - { label: "Align Content", name: "align", widget: "select", options: [ "left", "center", "right" ] }
          - {
            "label": "Comes with fries",
            "name": "fries",
            "widget": "boolean",
            "help": "Whether the course includes fries or not."
          }
