content-dir: content
collections:
  - name: page
    label: Page
    category: Content
    folder: content
    fields:
      - {"label": "Title", "name": "title", "widget": "string", "required": true}
      - {"label": "Body", "name": "body", "widget": "markdown"}
      - {
        "label": "Tags",
        "default": [ "Design" ],
        "max": 2,
        "min": 1,
        "multiple": true,
        "name": "tags",
        "options": [ "Design", "UX", "Dev" ],
        "widget": "select"
        }
      - {
        "label": "PDFs",
        "name": "pdfs",
        "widget": "relation",
        "collection": "resource",
        "display_field": "title",
        "multiple": true,
        "max": 10,
        "min": 1,
        "filter": { field: "filetype", filter_type: "equals", value: "PDF"}
        }
      - name: address
        label: Address
        widget: object
        required: false
        fields:
          - { label: "Street Address", name: "street_address", widget: "string", required: true }
          - { label: "City", name: "city", widget: "string", required: true }
          - { label: "State", name: "state", widget: "string", required: true }
          - { label: "Zip Code", name: "zip", widget: "string", required: true }

  - name: resource
    label: Resource
    category: Content
    folder: content
    fields:
      - {"label": "Title", "name": "title", "widget": "string", "required": true}
      - {"label": "Description", "name": "description", "widget": "text"}
      - {"label": "File", "name": "file", "widget": "file"}
      - {
        "label": "File Type",
        "required": true,
        "name": "filetype",
        "options": [ "PDF", "Word Doc", "PPT" ],
        "widget": "select"
        }

  - name: metadata
    label: Metadata
    category: Settings
    files:
      - file: data/metadata.json
        name: sitemetadata
        label: Site Metadata
        fields:
          - { "label": "Course Title", "name": "title", "widget": "text", "required": true }
          - {
            "label": "Course Description",
            "name": "description",
            "widget": "markdown",
            "minimal": true,
            "help": "A description of the course that will be shown on the course site home page."
          }
          - { "label": "Tags", "default": [ "Design" ], "max": 3, "min": 1, "multiple": true, "name": "tags", "options": [ "Design", "UX", "Dev" ], "widget": "select" }
          - { label: "Align Content", name: "align", widget: "select", options: [ "left", "center", "right" ] }
          - {
            "label": "Comes with fries",
            "name": "fries",
            "widget": "boolean",
            "help": "Whether the course includes fries or not."
          }
